### ISSUE TITLE
integration with SciDart

### ISSUE THREAD

**Issue by angelopolotto** [axegon/SkLite-dart#1]
Hello,
I've been working in a project called SciDart (https://scidart.org). The project goal is unify all the main Scientific algorithms in Dart.
I like the SkLite project and I thinking if it is possible join SciDart and SkLite.
Do you think if the joint is a good way to go?
I'm sending this issue because I can't find another communication channel.

**Comment by axegon** [comment]
Hi Angelo,

Honestly I don't have any problems with it. Quick glance over SciDart, I can see several things that could be beneficial here as well. I was specifically targeting Flutter given that most of the algorithms are(relatively) cheap to run and would do fine on most mid and high-end mobile devices. But to be fair, very little is strictly bonding this to Flutter and that can be de-coupled easily if needed. Full disclosure here: I hate dealing with web and anything UI-related, which is , for better or worse, the only other use case for Dart.

I am on Gitter btw so you can reach me there.
