### ISSUE TITLE
Models won't load in sklite Flutter

### ISSUE THREAD

**Issue by fvidjaja** [axegon/SkLite-dart#2]
While testing the library we observed that that all models except DecisionTree won't load. I found out that the exported JSON files are read wrongly in the Constructors of the models specifically the classes data. The commit from my fork  https://github.com/fvidjaja/SkLite-dart/commit/05062be7bca8ab72e00abf22a99e40057fe4b90e should fix this issue.

**Comment by axegon** [comment]
True, good catch. Please open a PR.

**Comment by axegon** [comment]
Now that I look at it, the better place to do it would likely be in the [sister project](https://github.com/axegon/sklite) and export the variables as `classes_` instead, to keep it consistent with scikit-learn.

**Comment by fvidjaja** [comment]
Alright, in that case I will change the DecisionTree model in this project and make the necessary changes in the sister project.

**Comment by axegon** [comment]
FYI, just fixed it in the sister project.

**Comment by axegon** [comment]
Should be fine here too now.
