### ISSUE TITLE
Null safety

### ISSUE THREAD

**Issue by TornadoStorm** [axegon/SkLite-dart#7]
This repository unfortunately hasn't been updated to have null safety. I have tested the repo from the pull request being made by @SebghatYusuf, but it, unfortunately, has a couple of bugs that needed to be ironed out. So far my fork of his fork seems to work in a stable condition. Please implement null safety or let me know if you want a merge from my branch :)

**Comment by axegon** [comment]
could you open a pr?

**Comment by TornadoStorm** [comment]
Sure! I'll get to it soon. I only made quick hotfixes for a small project so not sure whether it's entirely stable.

**Comment by axegon** [comment]
Appreciated!

**Comment by Parfyonator** [comment]
Hi @axegon.

That's great. Would you be able to update the package at pub.dev? It still can be used though the github dependency in pubspec but I guess it would be more convenient to get it from pub.dev.

**Comment by axegon** [comment]
@Parfyonator you're right, thanks for bringing it up(and sorry for the delay, I don't go on github often). It's been published under version `1.0.0`.

**Comment by Parfyonator** [comment]
Thank you!
